import 'bootstrap/dist/css/bootstrap.min.css'
import { Container, SSRProvider } from '@/components/bootstrap'
import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'
import  {SessionProvider}  from '@/components/session'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Authentication App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session:any;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <SSRProvider>
            <NavBar/>
            
            <main>
              <Container className='py-4'>
                {children}
              </Container>
            </main>
          </SSRProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
